modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"

[[mods]]
modId="termslime"
version="1.1.0"
displayName="slime's Mod"
credits="the mod made with MCreator - https://mcreator.net"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="termSlime, EagererScrollJava65, MCreator, user, RblxLuauDevCode"
description='''
the mod adds slime mobs, electronic blocks / items, armors, commands, constructing blocks, mob related items, etc.
'''

[[dependencies.termslime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




